from pluggit import Pluggit

test = Pluggit("192.168.188.117")
# test = Pluggit("klaus")
# test.__check_connection()

print("Unit: " + str(test.get_unit_type()))
# print("{:0.1f}".format(test.getTemperatureT1()) + "°C")
print("T1: " + str(test.get_temperature_t1()))
print("T2: " + str(test.get_temperature_t2()))
print("T3: " + str(test.get_temperature_t3()))
print("T4: " + str(test.get_temperature_t4()))
print("Serial Number: " + str(test.get_serial_number()))
print("Firmware-Version: " + str(test.get_firmware_version()))
print("Work Time: " + str(test.get_work_time()))
# test.set_date_time()
print("Current Mode: " + str(test.get_current_unit_mode()))
# test.set_unit_mode(ActiveUnitMode.MANUAL_MODE)
# test.set_unit_mode(ActiveUnitMode.WEEK_PROGRAM_MODE)
print("Speed Level: " + str(test.get_speed_level()))
# test.set_speed_level(SpeedLevelFan.LEVEL_1)
print("Remaining Filter Time: " + str(test.get_remaining_filter_time()))
# test.reset_filter()
print("Degree of Dirt: " + str(test.get_filter_dirtiness()))
print("Tmin: " + str(test.get_bypass_tmin()))
print("Tmax: " + str(test.get_bypass_tmax()))
# test.set_bypass_tmin(13)
# test.set_bypass_tmax(25)
print("Tmin Summer: " + str(test.get_bypass_tmin_summer()))
print("Tmax Summer: " + str(test.get_bypass_tmax_summer()))
# test.set_bypass_tmin_summer(15)
# test.set_bypass_tmax_summer(28)
print("Bypass State: " + str(test.get_bypass_actual_state()))
print("Bypass Timeout: " + str(test.get_bypass_manual_timeout()))
# test.set_bypass_manual_timeout(60)
